version: "3.8"

services:
  docdb:
    container_name: mongodbinfra
    image: mongo:4.2
    command: mongod --port 9090
    ports:
      - 9091:9090
    environment:
      # - TERM=xterm-256color
      - DEBUG=docdb*
      #- MONGO_INITDB_ROOT_USERNAME: admin 
      #- MONGO_INITDB_ROOT_PASSWORD: test 
    networks:
      infra:

networks:
  infra:
    driver: bridge

volumes:
  esdata02:
    driver: local